# Generated by Django 3.2.3 on 2021-06-01 18:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile-pictures/default.png', upload_to=users.models.profile_picture_name),
        ),
    ]
